version: '3'
services:
  client:
    container_name: "dndapp-client"
    image: dndapp-client:latest
    env_file: ".env"
    ports:
      - "${CLIENTPORT}:80"
  server:
    container_name: "dndapp-server"
    image: dndapp-server:latest
    env_file: ".env"\
    restart: always 
    ports:
      - "${SERVERPORT}:5000"