version: '3'
services:
  client:
    container_name: "dndapp-client"
    image: registry.jvdt.dev:5001/jordyjordy/dndapp-client
    env_file: ".env"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    ports:
      - "${CLIENTPORT}:80"
    labels:
      - "com.centurylinklabs.watchtower.scope=dndapp"
  server:
    container_name: "dndapp-server"
    image: registry.jvdt.dev:5001/jordyjordy/dndapp-server
    env_file: ".env"
    deploy:
      restart_policy:
        condition: any 
        delay: 10s
        window: 120s
    ports:
      - "${SERVERPORT}:5000"
    labels:
      - "com.centurylinklabs.watchtower.scope=dndapp"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 30 --scope dndapp
    labels:
      - "com.centurylinklabs.watchtower.scope=dndapp"